version: '3.8'
services:
  xbox-controller:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - DISPLAY
    network_mode: host
    devices:
      - "/dev/bus/usb/001/001:/dev/bus/usb/001/001"  # Adjust based on your controller's device path