services:
  xbox-controller:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - DISPLAY
    network_mode: host
    devices:
      - "/dev/input/js0:/dev/input/js0"  # Adjust based on your controller's device path